### ISSUE TITLE
Failed to activate the autocomplete-snippets package

### ISSUE THREAD

**Issue by aaronr93** [atom/autocomplete-snippets#45]
1. Exception thrown at startup and upon opening config: http://puu.sh/gXEr6/fe408129cb.png
2. Another exception is thrown simultaneously: https://github.com/atom-community/autocomplete-plus/issues/312 

There is a deprecated call in atom core:
atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use atom.views.getView(atom.workspace), which returns an HTMLElement.
Called 1 time.
Atom.Object.defineProperty.get - C:\Users\[MYUSER]\AppData\Local\atom\app-0.188.0\resources\app\src\atom.js:54:11
Object.activate - C:\Users\[MYUSER]\.atom\packages\autocomplete-plus-async\lib\autocomplete.coffee:31:31

**Atom Version**: 0.188.0
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [autocomplete-snippets](https://github.com/atom-community/autocomplete-snippets) package, v1.2.0

### Stack Trace

Failed to activate the autocomplete-snippets package

```
At Cannot find module 'fuzzaldrin'

Error: Cannot find module 'fuzzaldrin'
    at Module._resolveFilename (module.js:351:15)
    at Function.Module._resolveFilename (C:\Users\rosenbergerga1\AppData\Local\atom\app-0.188.0\resources\app\src\module-cache.js:383:52)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/C:/Users/rosenbergerga1/.atom/packages/autocomplete-snippets/lib/snippets-provider.coffee:6:16)
    at Object.<anonymous> (/C:/Users/rosenbergerga1/.atom/packages/autocomplete-snippets/lib/snippets-provider.coffee:54:4)
    at Module._compile (module.js:475:26)
    at Object.requireCoffeeScript (C:\Users\rosenbergerga1\AppData\Local\atom\app-0.188.0\resources\app\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
    at Module.load (module.js:370:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-mustache",
      "language-coffee-script",
      "language-clojure",
      "language-less",
      "language-make",
      "language-objective-c",
      "language-perl",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sass",
      "language-todo",
      "language-yaml",
      "metrics",
      "spell-check"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.15.0
autocomplete-css, v0.6.0
autocomplete-html, v0.5.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.7.1
autocomplete-snippets, v1.2.0
highlight-selected, v0.9.1
simple-drag-drop-text, v0.2.2
Sublime-Style-Column-Selection, v1.2.3

# Dev
No dev packages
```

**Comment by benogle** [comment]
This should be fixed. I'm sure you've updated everything to the latest version.
