### ISSUE TITLE
Error message in atom

### ISSUE THREAD

**Issue by ClavdiaChauchat** [atom/autocomplete-snippets#52]
Hi. Any ideas as to what I can do with this? 

Unexpected token } in /Users/____/.atom/packages/autocomplete-snippets/package.json

SyntaxError: Unexpected token }
    at Object.parse (native)
    at parseObject (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:54:19)
    at parseContentsSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:67:14)
    at Object.module.exports.readFileSync (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/season/lib/cson.js:156:14)
    at Function.module.exports.Package.loadMetadata (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:67:29)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:344:38)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:325:14)
    at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:633:21)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
  at /Users/____/.atom/packages/autocomplete-snippets/package.json:1:1

Thanks.

**Comment by lee-dohm** [comment]
Have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/hacking-atom-debugging)? Also, could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?

**Comment by benogle** [comment]
Closing this out as there has been no response in 2 months. If there is more information available and it is still happening, please reopen.
